### ISSUE TITLE
“SyntaxError: Use of const in strict mode.”

### ISSUE THREAD

**Issue by ndarville** [srn/currency#8]
I’m running into this error right after installing.

```sh
$ currency --help

/usr/local/lib/node_modules/currency/cli.js:8
const updateNotifier = require('update-notifier');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Det ser ellers ud som en lækker Node-pakke. 👀

**Comment by ndarville** [comment]
Never mind! I missed that npm can’t upgrade it self to >=4.0. Installing `n` fixed it.
